stages:
  - test
  - build

test:
  stage: test
  image: node:18
  script:
    - yarn test

build:
  stage: build
  image: node:18
  script:
    - yarn config set cache-folder .yarn
    - yarn --cache-folder .yarn
    - CI=false yarn build
    - CI=false yarn build-storybook
  artifacts:
    expire_in: 1 day
    paths:
      - storybook-static/
  tags:
    - merapi
  only:
    - master
