stages:
  - build

build-library:
  stage: build
  image: node:18
  script:
    - yarn config set cache-folder .yarn
    - yarn --cache-folder .yarn
    - CI=false yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - build/
  tags:
    - merapi
  only:
    - master

build-storybook:
  stage: build
  image: node:18
  script:
    - yarn config set cache-folder .yarn
    - yarn --cache-folder .yarn
    - CI=false yarn build-storybook
  artifacts:
    expire_in: 1 day
    paths:
      - build/
  tags:
    - merapi
  only:
    - master
